server:
  port: 8081
  forward-headers-strategy: FRAMEWORK # Gateway HATEOAS urls to point to gateway

spring:
  application:
    name: api-v0-questions
  data:
    mongodb:
      authentication-database: admin
      host: ${mongodb.host}
      port: ${mongodb.port:27017}
      database: ${mongodb.database}
      username: ${mongodb.username}
      password: ${mongodb.password}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${oauth.issuer-uri}
          
# See: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}