spring:
  data:
    mongodb:
      uri: YOUR_MONGO_URI
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${okta-domain}/oauth2/default
          
# See: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver